/*
 * Copyright (c) 2026 EdgeImpulse Inc.
 *
 * Generated by Edge Impulse and licensed under the applicable Edge Impulse
 * Terms of Service. Community and Professional Terms of Service
 * (https://edgeimpulse.com/legal/terms-of-service) or Enterprise Terms of
 * Service (https://edgeimpulse.com/legal/enterprise-terms-of-service),
 * according to your product plan subscription (the “License”).
 *
 * This software, documentation and other associated files (collectively referred
 * to as the “Software”) is a single SDK variation generated by the Edge Impulse
 * platform and requires an active paid Edge Impulse subscription to use this
 * Software for any purpose.
 *
 * You may NOT use this Software unless you have an active Edge Impulse subscription
 * that meets the eligibility requirements for the applicable License, subject to
 * your full and continued compliance with the terms and conditions of the License,
 * including without limitation any usage restrictions under the applicable License.
 *
 * If you do not have an active Edge Impulse product plan subscription, or if use
 * of this Software exceeds the usage limitations of your Edge Impulse product plan
 * subscription, you are not permitted to use this Software and must immediately
 * delete and erase all copies of this Software within your control or possession.
 * Edge Impulse reserves all rights and remedies available to enforce its rights.
 *
 * Unless required by applicable law or agreed to in writing, the Software is
 * distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
 * either express or implied. See the License for the specific language governing
 * permissions, disclaimers and limitations under the License.
 */
// Generated on: 23.03.2026 11:37:19

#include <stdio.h>
#include <stdlib.h>
#include "edge-impulse-sdk/tensorflow/lite/c/builtin_op_data.h"
#include "edge-impulse-sdk/tensorflow/lite/c/common.h"
#include "edge-impulse-sdk/tensorflow/lite/micro/micro_mutable_op_resolver.h"
#include "edge-impulse-sdk/porting/ei_classifier_porting.h"

#if EI_CLASSIFIER_PRINT_STATE
#if defined(__cplusplus) && EI_C_LINKAGE == 1
extern "C" {
    extern void ei_printf(const char *format, ...);
}
#else
extern void ei_printf(const char *format, ...);
#endif
#endif

#define STRINGIZE(x) #x
#define STRINGIZE_VALUE_OF(x) STRINGIZE(x)

#if defined (__GNUC__)  /* GNU compiler */
#define ALIGN(X) __attribute__((aligned(X)))
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (_MSC_VER)
#define ALIGN(X) __declspec(align(X))
#elif defined (__TASKING__) /* TASKING Compiler */
#define ALIGN(X) __align(X)
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (__ARMCC_VERSION) /* Arm Compiler */
#define ALIGN(X) __ALIGNED(x)
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (__ICCARM__) /* IAR Compiler */
#define ALIGN(x) __attribute__((aligned(x)))
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (__clang__) /* LLVM/Clang Compiler */
#define ALIGN(X) __ALIGNED(x)
#define DEFINE_SECTION(x) __attribute__((section(x)))
#endif

#if defined(EI_MODEL_SECTION) && (defined(__GNUC__) || defined(__clang__))
#define MODEL_SECTION(X) __attribute__((section(STRINGIZE_VALUE_OF(X))))
#else
#define MODEL_SECTION(X)
#endif

#ifndef EI_MAX_SCRATCH_BUFFER_COUNT
#ifndef CONFIG_IDF_TARGET_ESP32S3
#define EI_MAX_SCRATCH_BUFFER_COUNT 4
#else
#define EI_MAX_SCRATCH_BUFFER_COUNT 4
#endif // CONFIG_IDF_TARGET_ESP32S3
#endif // EI_MAX_SCRATCH_BUFFER_COUNT

#ifndef EI_MAX_OVERFLOW_BUFFER_COUNT
#define EI_MAX_OVERFLOW_BUFFER_COUNT 10
#endif // EI_MAX_OVERFLOW_BUFFER_COUNT

using namespace tflite;
using namespace tflite::ops;
using namespace tflite::ops::micro;

namespace {

#if defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX) || defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX_GNU)
constexpr int kTensorArenaSize = 1552;
#else
constexpr int kTensorArenaSize = 528;
#endif

#if defined(EI_CLASSIFIER_ALLOCATION_STATIC)
#if defined (EI_TENSOR_ARENA_LOCATION)
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16) DEFINE_SECTION(STRINGIZE_VALUE_OF(EI_TENSOR_ARENA_LOCATION));
#else
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16);
#endif
#elif defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX)
#pragma Bss(".tensor_arena")
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16);
#pragma Bss()
#elif defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX_GNU)
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16) __attribute__((section(".tensor_arena")));
#else
#define EI_CLASSIFIER_ALLOCATION_HEAP 1
uint8_t* tensor_arena = NULL;
#endif

static uint8_t* tensor_boundary;
static uint8_t* current_location;

template <int SZ, class T> struct TfArray {
  int sz; T elem[SZ];
};

enum used_operators_e {
  OP_FULLY_CONNECTED, OP_SOFTMAX,  OP_LAST
};

struct TensorInfo_t { // subset of TfLiteTensor used for initialization from constant memory
  TfLiteAllocationType allocation_type;
  TfLiteType type;
  void* data;
  TfLiteIntArray* dims;
  size_t bytes;
  TfLiteQuantization quantization;
};

typedef struct {
  TfLiteTensor tensor;
  int16_t index;
} TfLiteTensorWithIndex;

typedef struct {
  TfLiteEvalTensor tensor;
  int16_t index;
} TfLiteEvalTensorWithIndex;

TfLiteContext ctx{};
static const int MAX_TFL_TENSOR_COUNT = 4;
static TfLiteTensorWithIndex tflTensors[MAX_TFL_TENSOR_COUNT];
static const int MAX_TFL_EVAL_COUNT = 4;
static TfLiteEvalTensorWithIndex tflEvalTensors[MAX_TFL_EVAL_COUNT];
TfLiteRegistration registrations[OP_LAST];

namespace g0 {
const TfArray<2, int> tensor_dimension0 = { 2, { 1,185 } };
const TfArray<1, float> quant0_scale = { 1, { 2.7338120937347412, } };
const TfArray<1, int> quant0_zero = { 1, { -124 } };
const TfLiteAffineQuantization quant0 = { (TfLiteFloatArray*)&quant0_scale, (TfLiteIntArray*)&quant0_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data1[4] = { -30, 11, -11, 24, };
const TfArray<1, int> tensor_dimension1 = { 1, { 4 } };
const TfArray<1, float> quant1_scale = { 1, { 0.00095650623552501202, } };
const TfArray<1, int> quant1_zero = { 1, { 0 } };
const TfLiteAffineQuantization quant1 = { (TfLiteFloatArray*)&quant1_scale, (TfLiteIntArray*)&quant1_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int8_t tensor_data2[4*10] = { 
  56, 94, 74, -52, 21, -72, -127, -32, 107, 34, 
  49, -40, -72, -84, -81, -88, 16, 29, -31, 10, 
  -75, 47, -61, -92, 51, -78, 90, 50, 6, -55, 
  14, -25, 1, 42, 17, -51, 70, -32, -54, -98, 
};
const TfArray<2, int> tensor_dimension2 = { 2, { 4,10 } };
const TfArray<1, float> quant2_scale = { 1, { 0.0064089610241353512, } };
const TfLiteAffineQuantization quant2 = { (TfLiteFloatArray*)&quant2_scale, (TfLiteIntArray*)&g0::quant1_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data3[10] = { -25, 25, -43, 17, 10, -18, 27, 14, -65, -4, };
const TfArray<1, int> tensor_dimension3 = { 1, { 10 } };
const TfArray<1, float> quant3_scale = { 1, { 0.0015614022267982364, } };
const TfLiteAffineQuantization quant3 = { (TfLiteFloatArray*)&quant3_scale, (TfLiteIntArray*)&g0::quant1_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int8_t tensor_data4[10*20] = { 
  38, -72, -72, 35, 92, 44, 108, -116, -10, -46, 9, 16, 86, 121, 47, -80, -4, -54, -61, 16, 
  -39, -118, 62, 72, 69, -15, -52, -89, -83, 28, -93, -54, 80, 46, 84, 104, -74, 67, -35, -19, 
  -39, -100, -20, 102, -57, -76, -57, 4, -55, -8, 22, 32, -14, -103, -30, -72, 65, -81, -104, -84, 
  56, 22, 95, 46, -59, 98, -68, -46, -32, 68, 114, 39, -52, -72, 2, -36, -20, -57, 99, 95, 
  -39, 52, -119, -34, -84, 49, -31, 22, -100, 51, 80, 58, -35, 56, 21, -121, -55, 105, 67, 48, 
  -105, 65, -80, 66, -21, -123, -19, 69, -115, -60, 84, 47, -67, 51, -26, -63, -60, 27, -79, -6, 
  101, 41, -64, -85, 94, 65, 21, -23, -21, -12, 65, 43, -74, -43, 14, -35, 57, 12, -27, -26, 
  -16, 87, 46, 32, -22, 83, 98, -112, 119, -19, -65, 121, 54, -33, -98, 24, 74, 23, 3, 96, 
  42, 49, 33, 38, 82, 47, -121, -54, -49, 25, 67, 19, 28, -118, -64, 98, -96, 94, -41, -23, 
  47, -66, -12, 13, 72, 127, -26, 7, 72, -83, -70, 51, -55, -49, 54, -13, -9, 94, 14, 71, 
};
const TfArray<2, int> tensor_dimension4 = { 2, { 10,20 } };
const TfArray<1, float> quant4_scale = { 1, { 0.0036966484040021896, } };
const TfLiteAffineQuantization quant4 = { (TfLiteFloatArray*)&quant4_scale, (TfLiteIntArray*)&g0::quant1_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data5[20] = { 3, -5, 0, 0, -4, 1, -2, 1, -3, -6, 3, -7, 0, -2, -2, 0, 4, 7, -4, -5, };
const TfArray<1, int> tensor_dimension5 = { 1, { 20 } };
const TfArray<1, float> quant5_scale = { 1, { 0.0089183161035180092, } };
const TfLiteAffineQuantization quant5 = { (TfLiteFloatArray*)&quant5_scale, (TfLiteIntArray*)&g0::quant1_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int8_t tensor_data6[20*185] = { 
  14, -48, -39, 56, 29, 42, 31, -15, 37, -24, 18, 39, -28, -18, 9, 66, 32, 58, -3, -7, 65, 8, 64, 30, -27, 56, -4, -7, -16, -24, 33, 41, 52, -20, -27, 43, -13, 34, 8, -28, 28, -2, -31, -9, -41, 48, -11, 51, -26, -30, -2, -40, 22, -10, -44, 36, 50, 36, 57, 36, 21, -23, 3, -37, -6, -36, 2, 17, 42, -5, 14, -42, -26, -6, -19, 6, 67, 27, -9, 55, 27, 12, 7, 33, 9, 25, -35, 9, -25, -37, 26, -1, -18, 53, 0, -43, 56, 33, -34, -13, 0, -44, 13, 32, -11, -20, -18, 7, -25, -17, 43, 9, 18, 53, -16, 55, -11, 31, -37, 33, 42, 18, 33, 69, -29, 12, 53, 20, 60, 8, -25, -13, 66, 29, 59, -8, 17, 63, 2, 18, 34, 10, -24, -28, -8, 1, -4, 34, -34, -26, 16, 33, -18, 51, 41, 6, 65, 41, -21, 27, 49, 67, 0, 6, 11, 5, -13, -14, 55, 68, -2, 14, 15, 7, 12, 60, 51, 46, -8, -17, 23, 40, -27, -14, 26, 
  -63, -15, 32, -6, -27, 0, 26, 27, 38, 61, -19, 35, 18, 24, 45, -14, 55, 39, 67, -16, 5, 10, 57, 4, 40, 39, 4, 51, -1, -24, 6, 62, 58, 63, 50, -2, -29, -17, 2, -26, -35, -42, 36, 23, 17, -27, 26, -48, -8, -13, -58, -16, -5, -21, -3, -59, -40, 51, 43, -31, -16, 42, -11, -9, 2, 14, 51, -39, 42, 0, 62, -14, 43, 3, -6, 39, -25, -43, -17, 32, -17, -66, -12, 15, 36, 17, 5, -23, 24, 2, 31, 30, 60, 27, 18, 44, -9, -28, 23, -31, 27, 65, 13, 7, -20, 38, 54, -18, 5, 6, 1, -61, 42, 8, -30, 29, 12, 19, -25, -21, 27, -32, -1, -13, 38, 9, 12, 33, -29, 61, -4, -1, 47, -2, 62, 45, -18, -3, 7, 47, -36, 21, 8, -9, 15, 46, 45, 37, -28, -22, -11, -26, -25, -8, -8, 48, 44, 59, -24, -13, -19, -31, 40, -12, -31, -5, -28, 20, -34, -1, 1, -21, 33, -6, 3, 46, 39, -5, -16, -19, -28, 24, 30, 28, 0, 
  49, -35, -53, -40, 14, -21, 36, 47, 53, 1, -31, 14, -39, 32, -23, 43, 24, 38, 9, 30, 51, -40, 37, -36, 15, -9, 55, 31, -26, -36, -20, 39, 31, -33, -3, -11, -46, -6, -13, -121, 25, 24, -48, -6, 21, -11, -26, -43, 17, -11, 23, -15, -8, 1, 30, -38, 6, 12, 9, -15, 55, -11, -4, 14, -14, 32, 16, -25, -9, -15, 0, -49, 7, 48, 3, -50, -77, 31, -23, -24, 31, -18, 27, 6, 10, 16, -6, 9, -37, 8, -27, 52, 21, -6, 61, 47, 29, 45, 30, 29, -37, -36, -19, -28, 34, -5, 61, 51, 15, 4, -15, 30, -26, -82, -23, -22, 23, 49, -14, 22, -26, 42, 53, -47, 44, 40, 12, 34, -42, -5, 25, -34, 5, 26, 24, 26, -25, 39, 27, 17, -13, 43, 55, 52, -36, 8, -45, 11, -16, -31, 49, -30, -23, -16, -3, 27, 5, -41, 15, -64, -24, 2, -25, 9, -38, -68, -58, -48, -53, -47, -75, -54, -33, -86, -57, -28, -10, -59, -59, -81, -3, -80, -36, 11, -67, 
  -47, 43, -3, 33, 3, 22, -12, 42, 19, -52, 32, 34, 17, 25, 13, -22, -47, -37, 5, 23, -47, 9, -46, -33, 19, 12, -50, 20, 31, 21, -36, 7, 33, -38, 16, -6, 36, -28, -29, 47, -41, 35, 5, 46, 57, -32, 9, -20, 46, 36, -12, 21, 14, -31, 45, -21, -19, -22, 0, 24, 84, 53, 82, 65, -7, -18, 64, -8, 4, -21, 60, 11, 3, 5, -11, -6, -49, 53, 21, 37, -11, 12, 1, -46, -52, -92, -48, -75, -16, -64, -38, -35, -79, -31, 20, -53, -61, -41, 9, -39, -39, -28, 29, -50, -53, -30, -23, -35, -11, -8, -65, -9, -3, 15, 3, 46, -50, -12, 19, -24, -72, 10, -44, -18, -84, -30, -52, -73, -29, -19, -86, -85, -60, 8, -42, -59, -57, -10, -23, 3, 6, 6, -20, -34, -22, -18, -48, -60, -34, -23, -11, -36, 37, 38, -59, 0, -6, 30, -60, -80, -58, -2, 7, 2, -61, 0, -42, -60, 1, -13, -66, -46, -26, -62, 11, -4, -5, 5, 8, -65, -23, 13, 28, 19, -11, 
  29, 17, 21, -46, -55, -53, 29, -27, -39, 16, -30, -5, -40, -38, -51, 13, 15, 19, -20, -28, -15, 32, -26, -24, -32, -13, 22, 20, -54, -57, 8, -49, 30, -53, -32, -42, -25, -61, 18, 21, -5, 6, -58, -32, 16, -45, 25, 18, -24, 22, 20, 24, -54, -27, -28, 36, 19, 26, 32, 16, -58, -55, 34, 34, -11, 15, -36, 37, -65, -26, -59, 0, 22, 4, 8, 12, -28, -25, -36, -33, 25, -63, 12, -51, 3, -44, -3, -52, 19, -33, -33, -12, -2, 19, -1, -13, -6, -25, -53, -54, -26, -60, 2, -28, 33, -37, -64, -26, -44, 3, -47, -16, -45, -17, 8, -15, -33, -49, -42, -20, 32, -29, -45, -21, -59, -12, 33, -55, -39, 7, -32, -25, 5, -24, -26, -27, 11, 13, -62, 22, 2, -7, 19, -4, 26, -63, 30, -5, -56, -34, -21, 14, -27, -30, 29, 58, 46, -22, 53, -30, -10, 43, -37, -2, -41, -24, 20, -7, 57, -6, -3, -37, -30, 39, 37, 17, -10, 37, -7, 26, -12, 13, 27, 26, 22, 
  -30, 31, 8, 4, -6, -49, 1, 46, -28, 5, -58, -31, -53, 13, -2, -13, -61, 1, -32, -13, -47, -59, -21, -42, 20, -31, -3, -28, -28, 33, -28, -24, 22, -50, -7, -68, 30, -35, 53, 89, 34, 14, -32, -10, 13, -47, -34, -33, 1, 32, 43, -3, 13, -24, 16, 24, 12, -16, 20, -1, 4, -61, 21, -54, -26, -15, -31, 29, 31, 14, 33, -33, 25, -52, -61, -19, 23, -8, 29, 1, -40, 22, -23, 48, -4, -41, 19, -19, 60, -11, -8, -20, -45, 29, -10, -14, -15, 12, -14, 21, -15, 7, 36, -35, 4, -5, 45, -45, 0, 14, -16, -15, 16, 45, 39, 11, 36, -36, 21, -26, -49, 25, -35, 10, 4, 55, -7, -21, -26, -54, 1, 17, -24, -20, 11, 51, 24, -37, 37, 49, 28, 0, -2, -22, 11, -25, 51, 60, 44, -20, 68, 25, 26, -38, 45, 4, -10, 48, -12, 5, 36, -43, 32, -35, 43, -43, 58, -22, 36, 13, 6, 49, -38, 8, -37, 21, -31, -9, 57, 31, 48, 24, -44, -35, -1, 
  22, -16, -20, -30, -31, -54, -20, 35, -20, 3, -4, -6, -1, 28, 19, -9, -23, -27, 50, 39, -24, 9, -24, 33, -22, -5, 52, -44, 41, 13, 34, -48, 0, -7, -41, 30, -45, 15, -33, 72, -12, 3, -10, -4, -34, -51, 43, -36, -12, -18, -39, 38, -51, 24, 8, -14, -3, 34, 22, -25, -41, -3, 30, -38, 17, 4, -56, 25, -45, -38, 0, 37, -24, 16, 1, 31, 22, 36, 17, -31, 29, 21, -8, 5, -40, -25, 22, 2, -35, -33, -48, 22, -32, 35, -29, -62, -36, -44, -59, -18, -44, -42, -10, -26, 38, -22, -23, -49, -41, -16, -15, 18, 42, -29, 2, -30, 23, -24, -49, -24, -32, 6, -49, -5, -25, -48, -10, 17, -18, -49, 17, -54, -11, 18, 27, 31, -52, 13, 27, 44, 11, 22, -29, -63, -48, -5, 25, -45, 31, 52, -31, 35, -15, 42, -19, -47, 8, -21, 34, -26, 51, 19, -7, -35, 35, -17, -18, 33, 39, 14, -50, 40, 33, 54, 26, -39, -48, -19, 21, -8, 35, -15, 48, 6, -25, 
  44, -22, 13, 48, 49, 22, 23, 29, -9, 53, -2, 59, -8, 31, -24, -40, -7, -17, -24, 60, 54, -23, -16, 10, 0, 61, -3, 27, -38, 3, 23, 59, 22, -34, -6, -36, 6, 22, 46, -8, -5, 20, 59, 58, 27, 5, 19, -36, -24, 33, -29, -6, -1, 18, -7, -22, -35, 47, 42, -44, -28, -7, 39, -28, 35, 23, 20, -12, -13, 61, -23, 17, -3, 29, 8, 5, -28, 37, -14, 34, 61, -42, 41, 7, 22, -40, 32, 34, 46, -6, 2, -31, 21, -17, -26, -6, -1, -28, 20, 64, 1, 46, 15, -29, 12, 1, -4, -27, 68, -3, -6, -31, 20, 25, 48, -17, 51, 4, -7, 33, -5, 27, 7, -32, 32, 31, -22, -30, 4, 6, 44, 10, 1, 23, -22, 43, 3, 3, 19, 9, 10, 45, 47, 58, 34, 47, 13, -30, 47, 28, 8, -9, 25, 41, 44, 25, -8, 16, 2, -5, 5, -33, 25, 2, 2, -9, -40, 32, -37, 0, 40, -4, -8, 18, -30, 43, -15, -38, -20, 5, 11, 54, -3, -16, -27, 
  17, 97, 46, -15, -49, 20, -18, -43, -18, -22, -11, 17, 16, -32, -6, -37, 6, -39, 35, -5, 31, 19, 30, 6, 16, 17, 21, -21, 27, -62, 12, -66, -25, -17, -59, -31, -62, 40, -22, 22, -40, -49, -53, -25, -50, 9, -26, -14, -36, 6, -57, -59, 45, -39, 20, 18, 0, 19, -15, -30, 22, -21, 36, -29, -9, -62, 32, 27, 23, -38, -35, -28, -7, -55, -24, -49, -28, -33, -44, 35, -35, -40, -53, -38, 28, -5, -18, 4, 17, 17, -11, -60, -59, -25, 26, -17, 32, -2, 7, -45, -51, -48, -40, 7, -9, 25, -25, -9, -3, -23, -40, 32, 11, 28, 31, 36, 9, -40, 34, -23, 24, 29, -9, -28, 15, -61, -3, 40, -57, 30, -57, 31, -61, -24, -47, -14, -50, 34, 0, 32, 32, -14, 25, -39, -52, -2, 12, -44, -47, -16, 6, 28, -22, -46, -38, 16, -67, -67, 9, -26, 12, -14, -11, -61, -32, -68, -62, -1, -8, -7, 22, -28, -15, 18, 21, -41, 19, -34, -75, -2, -66, -39, -60, -40, -23, 
  -47, 7, -35, -16, -42, 22, -54, -6, -32, -57, -46, -37, -51, -15, -31, 43, -3, 33, 42, -29, -4, 40, 16, 55, 60, 45, 11, 24, 8, 33, -14, -3, -29, 9, 47, 26, 45, 32, -24, -9, -4, 10, -39, 2, -33, -62, 23, 11, 35, -51, 16, 40, -60, -59, -40, 0, 20, -4, -56, 7, -56, -37, -45, 31, -8, -21, -58, -23, -44, 14, -41, 26, 37, -7, -17, -50, 36, -31, -67, 25, 16, 40, -53, -38, -46, 31, -44, -35, 18, 3, 34, 13, -22, -13, -1, 41, -7, -54, -45, -28, 27, -44, -49, -23, 3, -6, -57, -27, 17, 15, 23, -36, -39, -40, 32, 23, 32, 20, 27, 18, 34, -58, -32, 38, -35, 18, 31, -24, -32, 15, -29, -36, -26, -20, -50, 18, 41, -6, 3, -56, 35, -40, 16, -7, 1, 14, 42, -8, -56, -12, -54, -58, -36, -39, 49, -38, -35, 33, -36, -1, -1, -41, 34, 33, 14, -39, -7, -14, 10, -18, 25, 52, 48, -2, -33, -17, 18, -23, 52, 5, -38, 13, 43, 53, 39, 
  52, -29, -27, -47, -47, -13, 35, 13, 1, 21, -35, 19, 17, -37, 28, -27, 2, 3, 22, 14, -40, 27, -44, 44, 46, -7, -22, -15, 39, 37, -47, -40, -39, -9, 54, 48, -11, -43, -46, -9, 33, 11, 6, -14, -15, 36, 6, -48, 32, 23, -18, -34, -13, -3, 35, 46, -38, -27, 11, -11, 14, 10, 26, 30, 11, -49, -44, 20, 17, 14, 42, 6, -6, -21, 20, 68, 51, -26, 27, 64, -8, -20, 33, -17, -3, 55, 3, 31, -7, -15, 11, 65, 34, -11, 2, 13, -18, 31, -36, 35, 51, 41, 27, 26, 33, -18, 9, -41, 40, 11, -11, -10, -7, -16, -35, 30, -15, 44, -19, -28, -25, -43, -28, -38, 44, 24, -35, 9, 22, -51, 35, -22, -39, -50, 17, 22, -5, -47, 49, 39, -20, -36, -22, 14, -7, -46, -2, -8, -7, -78, 23, 34, 30, 36, -40, -42, -35, -8, -23, -16, 25, -65, 16, -8, -31, -29, -24, -70, -35, -32, 2, -56, -57, -84, -2, 10, -19, -38, -16, 10, -27, -84, -20, -79, -46, 
  -24, -9, 71, -35, -59, -63, 36, -36, 23, -28, 30, 33, 18, 32, -34, 9, -36, -33, 33, -13, -25, -25, 36, -12, 2, 7, 19, 11, 39, 6, -18, -24, -11, -35, 0, -25, -49, 7, -6, 13, 4, 19, 27, -26, -45, -33, -4, 8, -61, -19, -54, 20, 2, 6, 36, 14, 11, -20, -9, -53, 28, 13, -16, -25, 22, 20, 23, -24, -21, -23, -51, -9, -39, -41, 28, -3, 1, 23, 4, -10, 4, 28, -62, -46, -67, -64, -51, 7, -20, 21, 12, -55, -65, -52, -3, 1, 10, 21, -22, -26, -19, -15, 27, 24, 19, 7, -9, 39, -11, -55, -20, 1, 7, 7, -66, -53, -66, -14, 18, 4, 38, 33, -10, -24, -17, -27, -40, -51, 40, 26, -45, 18, 8, -23, -59, -4, -54, 22, -40, 14, -20, -8, -24, 5, 18, -64, -13, -42, -40, -29, 19, -50, -28, -8, -19, 7, 14, 41, -16, -23, 35, -27, -7, 17, -55, 15, -30, -40, 26, 2, 9, -6, 35, -31, 37, -10, 38, 44, -19, 34, -28, 36, 17, 29, -44, 
  -36, -59, 24, -18, 29, -52, -49, -72, -67, 4, -39, -78, -13, 4, -46, 13, -21, -45, 15, -42, -1, 4, -60, 7, 0, -44, -24, -47, 21, -40, -46, -2, -78, 24, 5, 7, 22, -37, -49, -23, -5, 11, -44, -29, -56, -23, 43, 25, -18, 47, 39, -56, -60, 0, -25, -54, -42, 20, -23, 27, -9, -31, -32, 39, 8, 15, 40, 21, 5, 39, -5, -23, 25, 36, 4, -82, -41, 42, -41, -50, -6, 12, 25, 2, 24, 17, -75, -59, -28, 1, -56, 39, 3, -12, -34, -45, 19, 7, 36, -8, -36, 28, 25, 12, -4, -45, -5, 39, 24, 7, -10, -25, -9, -23, -40, 1, -44, -44, 22, -3, -1, -31, -9, -49, -14, 16, -83, -2, -33, 41, -37, 21, 23, -13, 10, 42, 27, -7, 37, 46, 32, 10, 42, -15, -22, -19, -52, 35, -38, -50, -1, -60, -30, -9, -25, 36, -53, 16, -31, -39, 25, -27, -64, -30, -49, -60, -11, 42, -31, -38, 35, -42, -59, 9, 14, 21, -31, 1, -36, -61, -50, -24, -26, -16, 29, 
  2, -75, -33, -9, 37, 44, -52, 41, -16, 4, 1, 4, 36, 5, -20, -46, -62, -18, -52, -29, -49, -51, -13, -27, -33, -64, -45, 34, -20, -7, 5, -62, -50, -62, -19, 2, 13, -14, 24, -54, 47, 28, 33, -48, 32, -37, -14, 17, 40, 20, 5, 11, -52, -37, 34, -34, -5, 23, 13, -24, -14, -32, -22, -52, 20, 27, 28, 27, -3, 34, -57, -23, 19, -24, 14, -52, -46, -28, 22, -38, -29, 13, -25, -27, 19, 0, 28, 35, -14, -63, -6, 3, -45, 16, -61, -48, -34, 38, -10, -38, -3, 32, -2, -51, -42, 11, -12, -17, -25, 9, 20, -57, -54, 5, -40, 20, 17, -40, 18, -58, -14, -31, -36, -31, 34, -5, -54, 26, 6, 31, -56, -53, -1, -16, -57, -62, 7, -35, -38, 30, 30, -21, 16, -64, -30, 21, 9, -37, 19, 39, -38, -44, -43, -54, -19, 33, -44, -23, 19, -36, -24, 20, 14, -3, -12, -13, 15, -60, -53, -36, 29, -38, 2, -5, -31, -57, -8, 20, -26, -15, 11, -54, -43, -4, -6, 
  38, 22, -40, 6, 3, -44, -38, 2, 8, 0, 32, -70, -63, 32, -70, -39, -66, -13, 8, -62, 21, 29, -48, 16, -71, -53, -29, -65, 17, -36, 30, -51, -47, 9, -31, -57, -67, 6, 41, -56, -60, 31, -57, 27, -15, 24, -28, -43, -59, -32, -21, 12, 7, -18, -48, -42, 37, -22, 35, -40, -7, 12, -41, 37, -3, 36, 34, 21, -20, 16, -7, -43, 34, -33, 40, 9, -24, 5, -12, -7, 17, -6, -49, -39, -5, -56, 24, -10, -57, -3, -36, 4, -20, 17, -59, -15, 25, 28, 28, 38, -62, 34, -47, 24, -56, -30, 20, -59, -36, -46, -40, -8, 39, 21, -55, 22, 40, -55, 28, 30, -41, -21, -19, -45, -51, -57, -19, 36, 34, -48, -31, -44, -13, -15, 21, 14, 33, 11, -58, 29, -30, 8, -28, -38, 25, 24, 6, -41, 18, 33, -37, -44, 33, 20, 13, -43, -32, 14, -32, -60, 0, 13, -16, -23, -59, -44, 1, -6, 16, -45, 10, 2, -43, -48, -65, 8, 28, 12, -2, 12, -71, -56, -61, -22, -6, 
  -9, 57, -39, -51, -50, 7, -12, 2, 14, 11, -9, 13, -35, 18, 19, 34, 3, 17, 13, 25, -53, 38, -48, 17, 6, -6, -30, -25, -16, -35, 7, -24, -25, 21, -11, 5, -9, -56, 23, 37, 36, -17, 9, -46, 28, -41, -56, -23, -47, 26, 11, -14, 27, 36, 11, -40, 36, 14, -47, 34, -8, -41, 1, -31, 0, 12, 0, -39, -5, 26, -52, 34, 34, 36, 12, 34, -32, 13, 46, 10, -45, -41, -4, 41, 42, 29, -3, 20, 22, 45, -6, 44, 2, 26, 42, 31, -48, 24, 25, 23, 37, 44, 45, -19, 33, -35, 8, 17, 49, -32, 14, -54, -50, 22, 21, -43, -29, -55, -11, -14, -36, 6, -8, -25, 12, -19, -39, -32, -22, -47, -16, -23, 6, 40, -38, -27, -33, -22, 1, 1, -36, 7, -31, -9, 35, 1, 43, -3, -14, -31, 23, -29, -30, 33, 24, 14, -32, 28, -33, -50, -36, 42, -49, 23, -3, -22, -52, 27, 26, -2, -18, -32, -36, -41, 21, 43, -13, -56, -51, -19, 46, -29, -41, -35, -20, 
  7, -127, -7, 3, 41, 2, -3, -21, 36, -28, -28, 1, 29, 42, -1, 37, -23, -8, 43, 2, -24, -10, 41, -3, 42, 2, 10, 59, -16, 58, 39, 19, 62, -10, 5, -8, 38, -40, -14, 1, 13, 9, 17, 45, 1, -33, 51, -38, 6, -8, 17, 6, 2, -29, 0, -41, 1, -3, 47, -24, -23, 54, -21, 15, -25, 33, 13, -7, 10, 60, -31, 2, -12, 56, 37, 49, -15, 25, -20, 21, 21, 56, -40, -3, 11, 50, 16, -19, 61, -2, 15, 61, 57, 18, 17, -16, 15, -6, 55, -14, 0, 2, -1, 1, 55, 42, 30, 55, 0, -21, 39, 15, 49, -20, -39, 23, -7, 55, -22, -33, 38, 5, -17, 7, 63, 25, 11, -33, 60, 59, 3, 54, 4, 22, -26, 10, 43, -31, 56, -38, 50, -6, 35, -17, -22, 22, 56, 44, 6, 6, 1, -2, 40, 34, 12, -12, 37, 59, -20, 2, -29, 35, 8, 56, 54, -14, 60, -33, 2, 25, 39, 5, 39, 51, 35, 1, 39, 52, -33, 60, 52, -6, -30, 40, 59, 
  -6, 109, 57, 66, 78, -11, -16, 43, 20, -15, -26, 41, -32, 24, -49, -34, -51, -2, 28, -45, 10, -42, -60, 33, -50, -60, -47, -6, -25, -52, -30, -59, -20, -8, -19, 29, 25, -23, 94, 44, -32, -4, 78, 7, 41, -7, 28, 76, -15, 40, -5, -11, 64, 46, 35, -27, 60, -28, -2, -11, 25, -24, 41, 56, 0, 36, 4, 7, 29, -1, 50, -6, 38, 58, 25, -7, -46, -18, 59, -36, -41, -49, -53, 0, 19, 35, -31, -4, 6, 17, -8, 39, -56, -39, 31, 16, 8, -36, 37, -62, 35, 13, 0, -37, -38, -59, -47, 43, 9, -63, -51, -15, 95, 32, -24, 16, 58, 70, -10, 3, -26, 51, 13, 46, 0, 24, 20, 45, 45, 44, 21, 21, -32, 39, 3, -14, 48, 35, 11, -17, -51, -48, -56, 37, 19, -9, 7, 6, 51, 51, -6, 71, -19, -8, 37, 11, 10, 37, 35, -10, -28, -23, -33, 17, 59, 62, -23, -1, 63, 33, -27, 11, 57, 63, 65, 63, 35, 30, -4, 57, 71, 62, 67, -9, -15, 
  -55, -16, 18, -62, 16, 14, -24, 3, 8, -8, -37, -7, -33, -26, -29, -17, 13, -20, -17, 30, -19, 53, -19, 51, -12, -34, 9, -4, -36, -26, 35, -12, -22, -36, 62, 51, 22, -47, -53, -14, -48, 1, -43, 15, -11, -20, 37, -1, -52, -63, 3, -35, 25, -25, 36, -33, -26, -27, -3, 45, -13, -18, -27, 44, 32, -20, 55, -34, 13, 51, 39, 34, 47, -12, -62, 11, 40, -1, -24, 6, 2, 9, 33, -1, 21, 10, 48, 8, 1, -34, -47, 43, 36, -13, -30, -32, 33, 16, 56, -22, -46, 59, 21, 15, -18, 6, -17, -28, 12, 38, -26, -3, -64, -37, -39, -48, 15, 13, -35, -35, 57, -17, -2, 22, 26, 62, 1, -9, 15, 16, -35, -13, 13, 9, 4, -17, 24, 61, -12, 26, 47, -5, 2, -11, 54, 49, 24, 27, -19, 3, 3, 9, 32, 17, 0, -14, 37, -11, 60, 3, 26, -12, 31, -30, -6, -34, -10, 61, 5, 41, 50, -28, 61, 48, 3, 36, -21, -16, 49, 41, 31, -12, -37, 56, 48, 
  -13, 51, 22, -38, -21, -29, 4, -18, 26, 24, -54, 30, 25, -12, -12, -33, -13, -55, -39, 3, -31, -59, 30, -52, -15, -10, -45, -33, 8, 30, -47, -3, 33, -44, -6, 7, -58, 0, -10, -20, -47, -49, 2, 17, -12, -54, -60, 2, -17, -10, 1, 12, -56, 6, 12, -39, 16, -55, -47, 32, -52, 23, -50, 7, -51, -17, -20, -47, -49, -42, -61, 23, -27, -19, -23, 6, -55, -64, -59, -35, 28, -15, -13, -56, -22, 7, 34, -17, 3, -11, -60, -4, -47, -23, 3, -55, -46, -49, 40, -43, -28, 28, 24, -52, -21, 21, -61, -48, -16, 19, 40, 27, -56, -45, 11, -5, -17, -41, -35, -16, 40, -4, 11, -38, 3, 22, -58, -12, -39, -11, -49, -11, 30, 17, -5, 39, 13, 29, -39, -33, 8, -45, 7, 2, -11, 29, -48, 29, -24, 8, -62, 15, -22, -30, -8, -59, -52, -21, -12, 17, -52, -61, 29, -27, 4, -52, 23, 19, 32, -44, -30, 22, 7, -24, -2, 19, -51, -8, -44, -28, 1, -46, -28, -17, -30, 
};
const TfArray<2, int> tensor_dimension6 = { 2, { 20,185 } };
const TfArray<1, float> quant6_scale = { 1, { 0.0032622271683067083, } };
const TfLiteAffineQuantization quant6 = { (TfLiteFloatArray*)&quant6_scale, (TfLiteIntArray*)&g0::quant1_zero, 0 };
const TfArray<2, int> tensor_dimension7 = { 2, { 1,20 } };
const TfArray<1, float> quant7_scale = { 1, { 0.42238321900367737, } };
const TfArray<1, int> quant7_zero = { 1, { -128 } };
const TfLiteAffineQuantization quant7 = { (TfLiteFloatArray*)&quant7_scale, (TfLiteIntArray*)&quant7_zero, 0 };
const TfArray<2, int> tensor_dimension8 = { 2, { 1,10 } };
const TfArray<1, float> quant8_scale = { 1, { 0.14924512803554535, } };
const TfLiteAffineQuantization quant8 = { (TfLiteFloatArray*)&quant8_scale, (TfLiteIntArray*)&g0::quant7_zero, 0 };
const TfArray<2, int> tensor_dimension9 = { 2, { 1,4 } };
const TfArray<1, float> quant9_scale = { 1, { 0.16960057616233826, } };
const TfArray<1, int> quant9_zero = { 1, { -38 } };
const TfLiteAffineQuantization quant9 = { (TfLiteFloatArray*)&quant9_scale, (TfLiteIntArray*)&quant9_zero, 0 };
const TfArray<1, float> quant10_scale = { 1, { 0.00390625, } };
const TfLiteAffineQuantization quant10 = { (TfLiteFloatArray*)&quant10_scale, (TfLiteIntArray*)&g0::quant7_zero, 0 };
const TfLiteFullyConnectedParams opdata0 = { kTfLiteActRelu, kTfLiteFullyConnectedWeightsFormatDefault, false, false };
const TfArray<3, int> inputs0 = { 3, { 0,6,5 } };
const TfArray<1, int> outputs0 = { 1, { 7 } };
const TfLiteFullyConnectedParams opdata1 = { kTfLiteActRelu, kTfLiteFullyConnectedWeightsFormatDefault, false, false };
const TfArray<3, int> inputs1 = { 3, { 7,4,3 } };
const TfArray<1, int> outputs1 = { 1, { 8 } };
const TfLiteFullyConnectedParams opdata2 = { kTfLiteActNone, kTfLiteFullyConnectedWeightsFormatDefault, false, false };
const TfArray<3, int> inputs2 = { 3, { 8,2,1 } };
const TfArray<1, int> outputs2 = { 1, { 9 } };
const TfLiteSoftmaxParams opdata3 = { 1 };
const TfArray<1, int> inputs3 = { 1, { 9 } };
const TfArray<1, int> outputs3 = { 1, { 10 } };
};

TensorInfo_t tensorData[] = {
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension0, 185, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant0))}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data1, (TfLiteIntArray*)&g0::tensor_dimension1, 16, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant1))}, },
{ kTfLiteMmapRo, kTfLiteInt8, (int32_t*)g0::tensor_data2, (TfLiteIntArray*)&g0::tensor_dimension2, 40, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant2))}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data3, (TfLiteIntArray*)&g0::tensor_dimension3, 40, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant3))}, },
{ kTfLiteMmapRo, kTfLiteInt8, (int32_t*)g0::tensor_data4, (TfLiteIntArray*)&g0::tensor_dimension4, 200, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant4))}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data5, (TfLiteIntArray*)&g0::tensor_dimension5, 80, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant5))}, },
{ kTfLiteMmapRo, kTfLiteInt8, (int32_t*)g0::tensor_data6, (TfLiteIntArray*)&g0::tensor_dimension6, 3700, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant6))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 192), (TfLiteIntArray*)&g0::tensor_dimension7, 20, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant7))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension8, 10, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant8))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 16), (TfLiteIntArray*)&g0::tensor_dimension9, 4, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant9))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension9, 4, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant10))}, },
};

#ifndef TF_LITE_STATIC_MEMORY
TfLiteNode tflNodes[4] = {
{ (TfLiteIntArray*)&g0::inputs0, (TfLiteIntArray*)&g0::outputs0, (TfLiteIntArray*)&g0::inputs0, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata0)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs1, (TfLiteIntArray*)&g0::outputs1, (TfLiteIntArray*)&g0::inputs1, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata1)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs2, (TfLiteIntArray*)&g0::outputs2, (TfLiteIntArray*)&g0::inputs2, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata2)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs3, (TfLiteIntArray*)&g0::outputs3, (TfLiteIntArray*)&g0::inputs3, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata3)), nullptr, 0, },
};
#else
TfLiteNode tflNodes[4] = {
{ (TfLiteIntArray*)&g0::inputs0, (TfLiteIntArray*)&g0::outputs0, (TfLiteIntArray*)&g0::inputs0, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata0)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs1, (TfLiteIntArray*)&g0::outputs1, (TfLiteIntArray*)&g0::inputs1, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata1)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs2, (TfLiteIntArray*)&g0::outputs2, (TfLiteIntArray*)&g0::inputs2, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata2)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs3, (TfLiteIntArray*)&g0::outputs3, (TfLiteIntArray*)&g0::inputs3, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata3)), nullptr, 0, },
};
#endif

used_operators_e used_ops[] =
{OP_FULLY_CONNECTED, OP_FULLY_CONNECTED, OP_FULLY_CONNECTED, OP_SOFTMAX, };


// Indices into tflTensors and tflNodes for subgraphs
const size_t tflTensors_subgraph_index[] = {0, 11, };
const size_t tflNodes_subgraph_index[] = {0, 4, };

// Input/output tensors
static const int in_tensor_indices[] = {
  0, 
};

static const int out_tensor_indices[] = {
  10, 
};


size_t current_subgraph_index = 0;

static void init_tflite_tensor(size_t i, TfLiteTensor *tensor) {
  tensor->type = tensorData[i].type;
  tensor->is_variable = false;

#if defined(EI_CLASSIFIER_ALLOCATION_HEAP)
  tensor->allocation_type = tensorData[i].allocation_type;
#else
  tensor->allocation_type = (tensor_arena <= tensorData[i].data && tensorData[i].data < tensor_arena + kTensorArenaSize) ? kTfLiteArenaRw : kTfLiteMmapRo;
#endif
  tensor->bytes = tensorData[i].bytes;
  tensor->dims = tensorData[i].dims;

#if defined(EI_CLASSIFIER_ALLOCATION_HEAP)
  if(tensor->allocation_type == kTfLiteArenaRw){
    uint8_t* start = (uint8_t*) ((uintptr_t)tensorData[i].data + (uintptr_t) tensor_arena);

    tensor->data.data =  start;
  }
  else {
      tensor->data.data = tensorData[i].data;
  }
#else
  tensor->data.data = tensorData[i].data;
#endif // EI_CLASSIFIER_ALLOCATION_HEAP
  tensor->quantization = tensorData[i].quantization;
  if (tensor->quantization.type == kTfLiteAffineQuantization) {
    TfLiteAffineQuantization const* quant = ((TfLiteAffineQuantization const*)(tensorData[i].quantization.params));
    tensor->params.scale = quant->scale->data[0];
    tensor->params.zero_point = quant->zero_point->data[0];
  }

}

static void init_tflite_eval_tensor(int i, TfLiteEvalTensor *tensor) {

  tensor->type = tensorData[i].type;

  tensor->dims = tensorData[i].dims;

#if defined(EI_CLASSIFIER_ALLOCATION_HEAP)
  auto allocation_type = tensorData[i].allocation_type;
  if(allocation_type == kTfLiteArenaRw) {
    uint8_t* start = (uint8_t*) ((uintptr_t)tensorData[i].data + (uintptr_t) tensor_arena);

    tensor->data.data =  start;
  }
  else {
    tensor->data.data = tensorData[i].data;
  }
#else
  tensor->data.data = tensorData[i].data;
#endif // EI_CLASSIFIER_ALLOCATION_HEAP
}

static void* overflow_buffers[EI_MAX_OVERFLOW_BUFFER_COUNT];
static size_t overflow_buffers_ix = 0;
static void * AllocatePersistentBufferImpl(struct TfLiteContext* ctx,
                                       size_t bytes) {
  void *ptr;
  uint32_t align_bytes = (bytes % 16) ? 16 - (bytes % 16) : 0;

  if (current_location - (bytes + align_bytes) < tensor_boundary) {
    if (overflow_buffers_ix > EI_MAX_OVERFLOW_BUFFER_COUNT - 1) {
      ei_printf("ERR: Failed to allocate persistent buffer of size %d, does not fit in tensor arena and reached EI_MAX_OVERFLOW_BUFFER_COUNT\n",
        (int)bytes);
      return NULL;
    }

    // OK, this will look super weird, but.... we have CMSIS-NN buffers which
    // we cannot calculate beforehand easily.
    ptr = ei_calloc(bytes, 1);
    if (ptr == NULL) {
      ei_printf("ERR: Failed to allocate persistent buffer of size %d\n", (int)bytes);
      return NULL;
    }
    overflow_buffers[overflow_buffers_ix++] = ptr;
    return ptr;
  }

  current_location -= bytes;

  // align to the left aligned boundary of 16 bytes
  current_location -= 15; // for alignment
  current_location += 16 - ((uintptr_t)(current_location) & 15);

  ptr = current_location;
  memset(ptr, 0, bytes);

  return ptr;
}

typedef struct {
  size_t bytes;
  void *ptr;
} scratch_buffer_t;

static scratch_buffer_t scratch_buffers[EI_MAX_SCRATCH_BUFFER_COUNT];
static size_t scratch_buffers_ix = 0;

static TfLiteStatus RequestScratchBufferInArenaImpl(struct TfLiteContext* ctx, size_t bytes,
                                                int* buffer_idx) {
  if (scratch_buffers_ix > EI_MAX_SCRATCH_BUFFER_COUNT - 1) {
    ei_printf("ERR: Failed to allocate scratch buffer of size %d, reached EI_MAX_SCRATCH_BUFFER_COUNT\n",
      (int)bytes);
    return kTfLiteError;
  }

  scratch_buffer_t b;
  b.bytes = bytes;

  b.ptr = AllocatePersistentBufferImpl(ctx, b.bytes);
  if (!b.ptr) {
    ei_printf("ERR: Failed to allocate scratch buffer of size %d\n",
      (int)bytes);
    return kTfLiteError;
  }

  scratch_buffers[scratch_buffers_ix] = b;
  *buffer_idx = scratch_buffers_ix;

  scratch_buffers_ix++;

  return kTfLiteOk;
}

static void* GetScratchBufferImpl(struct TfLiteContext* ctx, int buffer_idx) {
  if (buffer_idx > (int)scratch_buffers_ix) {
    return NULL;
  }
  return scratch_buffers[buffer_idx].ptr;
}

static const uint16_t TENSOR_IX_UNUSED = 0x7FFF;

static void ResetTensors() {
  for (size_t ix = 0; ix < MAX_TFL_TENSOR_COUNT; ix++) {
    tflTensors[ix].index = TENSOR_IX_UNUSED;
  }
  for (size_t ix = 0; ix < MAX_TFL_EVAL_COUNT; ix++) {
    tflEvalTensors[ix].index = TENSOR_IX_UNUSED;
  }
}

static TfLiteTensor* GetTensorImpl(const struct TfLiteContext* context,
                               int tensor_idx) {

  tensor_idx = tflTensors_subgraph_index[current_subgraph_index] + tensor_idx;

  for (size_t ix = 0; ix < MAX_TFL_TENSOR_COUNT; ix++) {
    // already used? OK!
    if (tflTensors[ix].index == tensor_idx) {
      return &tflTensors[ix].tensor;
    }
    // passed all the ones we've used, so end of the list?
    if (tflTensors[ix].index == TENSOR_IX_UNUSED) {
      // init the tensor
      init_tflite_tensor(tensor_idx, &tflTensors[ix].tensor);
      tflTensors[ix].index = tensor_idx;
      return &tflTensors[ix].tensor;
    }
  }

  ei_printf("ERR: GetTensor called beyond MAX_TFL_TENSOR_COUNT (%d)\n", MAX_TFL_TENSOR_COUNT);
  return nullptr;
}

static TfLiteEvalTensor* GetEvalTensorImpl(const struct TfLiteContext* context,
                                       int tensor_idx) {

  tensor_idx = tflTensors_subgraph_index[current_subgraph_index] + tensor_idx;

  for (size_t ix = 0; ix < MAX_TFL_EVAL_COUNT; ix++) {
    // already used? OK!
    if (tflEvalTensors[ix].index == tensor_idx) {
      return &tflEvalTensors[ix].tensor;
    }
    // passed all the ones we've used, so end of the list?
    if (tflEvalTensors[ix].index == TENSOR_IX_UNUSED) {
      // init the tensor
      init_tflite_eval_tensor(tensor_idx, &tflEvalTensors[ix].tensor);
      tflEvalTensors[ix].index = tensor_idx;
      return &tflEvalTensors[ix].tensor;
    }
  }

  ei_printf("ERR: GetTensor called beyond MAX_TFL_EVAL_COUNT (%d)\n", (int)MAX_TFL_EVAL_COUNT);
  return nullptr;
}

class EonMicroContext : public MicroContext {
 public:
 
  EonMicroContext(): MicroContext(nullptr, nullptr, nullptr) { }

  void* AllocatePersistentBuffer(size_t bytes) {
    return AllocatePersistentBufferImpl(nullptr, bytes);
  }

  TfLiteStatus RequestScratchBufferInArena(size_t bytes,
                                           int* buffer_index) {
  return RequestScratchBufferInArenaImpl(nullptr, bytes, buffer_index);
  }

  void* GetScratchBuffer(int buffer_index) {
    return GetScratchBufferImpl(nullptr, buffer_index);
  }
 
  TfLiteTensor* AllocateTempTfLiteTensor(int tensor_index) {
    return GetTensorImpl(nullptr, tensor_index);
  }

  void DeallocateTempTfLiteTensor(TfLiteTensor* tensor) {
    return;
  }

  bool IsAllTempTfLiteTensorDeallocated() {
    return true;
  }

  TfLiteEvalTensor* GetEvalTensor(int tensor_index) {
    return GetEvalTensorImpl(nullptr, tensor_index);
  }

};


} // namespace

TfLiteStatus tflite_learn_936190_47_init( void*(*alloc_fnc)(size_t,size_t) ) {
#ifdef EI_CLASSIFIER_ALLOCATION_HEAP
  tensor_arena = (uint8_t*) alloc_fnc(16, kTensorArenaSize);
  if (!tensor_arena) {
    ei_printf("ERR: failed to allocate tensor arena\n");
    return kTfLiteError;
  }
#else
  memset(tensor_arena, 0, kTensorArenaSize);
#endif
  tensor_boundary = tensor_arena;
  current_location = tensor_arena + kTensorArenaSize;

  EonMicroContext micro_context_;
  
  // Set microcontext as the context ptr
  ctx.impl_ = static_cast<void*>(&micro_context_);
  // Setup tflitecontext functions
  ctx.AllocatePersistentBuffer = &AllocatePersistentBufferImpl;
  ctx.RequestScratchBufferInArena = &RequestScratchBufferInArenaImpl;
  ctx.GetScratchBuffer = &GetScratchBufferImpl;
  ctx.GetTensor = &GetTensorImpl;
  ctx.GetEvalTensor = &GetEvalTensorImpl;
  ctx.ReportError = &MicroContextReportOpError;

  ctx.tensors_size = 11;
  for (size_t i = 0; i < 11; ++i) {
    TfLiteTensor tensor;
    init_tflite_tensor(i, &tensor);
    if (tensor.allocation_type == kTfLiteArenaRw) {
      auto data_end_ptr = (uint8_t*)tensor.data.data + tensorData[i].bytes;
      if (data_end_ptr > tensor_boundary) {
        tensor_boundary = data_end_ptr;
      }
    }
  }

  if (tensor_boundary > current_location /* end of arena size */) {
    ei_printf("ERR: tensor arena is too small, does not fit model - even without scratch buffers\n");
    return kTfLiteError;
  }

  registrations[OP_FULLY_CONNECTED] = Register_FULLY_CONNECTED();
  registrations[OP_SOFTMAX] = Register_SOFTMAX();

  for (size_t g = 0; g < 1; ++g) {
    current_subgraph_index = g;
    for(size_t i = tflNodes_subgraph_index[g]; i < tflNodes_subgraph_index[g+1]; ++i) {
      if (registrations[used_ops[i]].init) {
        tflNodes[i].user_data = registrations[used_ops[i]].init(&ctx, (const char*)tflNodes[i].builtin_data, 0);
      }
    }
  }
  current_subgraph_index = 0;

  for(size_t g = 0; g < 1; ++g) {
    current_subgraph_index = g;
    for(size_t i = tflNodes_subgraph_index[g]; i < tflNodes_subgraph_index[g+1]; ++i) {
      if (registrations[used_ops[i]].prepare) {
        ResetTensors();
        TfLiteStatus status = registrations[used_ops[i]].prepare(&ctx, &tflNodes[i]);
        if (status != kTfLiteOk) {
          return status;
        }
      }
    }
  }
  current_subgraph_index = 0;

  return kTfLiteOk;
}

TfLiteStatus tflite_learn_936190_47_input(int index, TfLiteTensor *tensor) {
  init_tflite_tensor(in_tensor_indices[index], tensor);
  return kTfLiteOk;
}

TfLiteStatus tflite_learn_936190_47_output(int index, TfLiteTensor *tensor) {
  init_tflite_tensor(out_tensor_indices[index], tensor);
  return kTfLiteOk;
}

TfLiteStatus tflite_learn_936190_47_invoke() {
  for (size_t i = 0; i < 4; ++i) {
    ResetTensors();

    TfLiteStatus status = registrations[used_ops[i]].invoke(&ctx, &tflNodes[i]);

#if EI_CLASSIFIER_PRINT_STATE
    ei_printf("layer %lu\n", i);
    ei_printf("    inputs:\n");
    for (size_t ix = 0; ix < tflNodes[i].inputs->size; ix++) {
      auto d = tensorData[tflNodes[i].inputs->data[ix]];

      size_t data_ptr = (size_t)d.data;

      if (d.allocation_type == kTfLiteArenaRw) {
        data_ptr = (size_t)tensor_arena + data_ptr;
      }

      if (d.type == TfLiteType::kTfLiteInt8) {
        int8_t* data = (int8_t*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes; jx++) {
          ei_printf("%d ", data[jx]);
        }
      }
      else {
        float* data = (float*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes / 4; jx++) {
          ei_printf("%f ", data[jx]);
        }
      }
      ei_printf("\n");
    }
    ei_printf("\n");

    ei_printf("    outputs:\n");
    for (size_t ix = 0; ix < tflNodes[i].outputs->size; ix++) {
      auto d = tensorData[tflNodes[i].outputs->data[ix]];

      size_t data_ptr = (size_t)d.data;

      if (d.allocation_type == kTfLiteArenaRw) {
        data_ptr = (size_t)tensor_arena + data_ptr;
      }

      if (d.type == TfLiteType::kTfLiteInt8) {
        int8_t* data = (int8_t*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes; jx++) {
          ei_printf("%d ", data[jx]);
        }
      }
      else {
        float* data = (float*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes / 4; jx++) {
          ei_printf("%f ", data[jx]);
        }
      }
      ei_printf("\n");
    }
    ei_printf("\n");
#endif // EI_CLASSIFIER_PRINT_STATE

    if (status != kTfLiteOk) {
      return status;
    }
  }
  return kTfLiteOk;
}

TfLiteStatus tflite_learn_936190_47_reset( void (*free_fnc)(void* ptr) ) {
#ifdef EI_CLASSIFIER_ALLOCATION_HEAP
  free_fnc(tensor_arena);
#endif

  // scratch buffers are allocated within the arena, so just reset the counter so memory can be reused
  scratch_buffers_ix = 0;

  // overflow buffers are on the heap, so free them first
  for (size_t ix = 0; ix < overflow_buffers_ix; ix++) {
    ei_free(overflow_buffers[ix]);
  }
  overflow_buffers_ix = 0;
  return kTfLiteOk;
}
