################################################################################
# Automatically-generated file. Do not edit!
################################################################################

CPP_UPPER_SRCS := 
ASM_UPPER_SRCS := 
C++M_SRCS := 
C++_UPPER_SRCS := 
CC_UPPER_SRCS := 
CPP_SRCS := 
O_SRCS := 
ELF_SRCS := 
CXX_SRCS := 
CCM_SRCS := 
LINKER_SCRIPT := 
SX_SRCS := 
JMP_UPPER_SRCS := 
P_UPPER_SRCS := 
X_SRCS := 
SRC_SRCS := 
X_UPPER_SRCS := 
CCM_UPPER_SRCS := 
JMP_SRCS := 
FSY_UPPER_SRCS := 
PP_UPPER_SRCS := 
CXXM_UPPER_SRCS := 
OBJ_UPPER_SRCS := 
ASM_SRCS := 
SX_UPPER_SRCS := 
O_UPPER_SRCS := 
CXX_UPPER_SRCS := 
S_UPPER_SRCS := 
ELF_UPPER_SRCS := 
C_UPPER_SRCS := 
C++_SRCS := 
OBJ_SRCS := 
S_SRCS := 
CC_SRCS := 
PP_SRCS := 
SRC_UPPER_SRCS := 
FSY_SRCS := 
P_SRCS := 
C++M_UPPER_SRCS := 
C_SRCS := 
CXXM_SRCS := 
CC_UPPER_DEPS := 
C++M_UPPER_DEPS := 
C++_UPPER_DEPS := 
CPP_UPPER_DEPS := 
FSY_DEPS := 
C_UPPER_DEPS := 
SECONDARY_SIZE := 
SRC_UPPER_DEPS := 
S_DEPS := 
CXXM_DEPS := 
PP_UPPER_DEPS := 
P_DEPS := 
CREF := 
OBJCOPY := 
JMP_UPPER_DEPS := 
ASM_UPPER_DEPS := 
CXX_DEPS := 
SX_UPPER_DEPS := 
CXX_UPPER_DEPS := 
JMP_DEPS := 
CCM_DEPS := 
P_UPPER_DEPS := 
CXXM_UPPER_DEPS := 
FSY_UPPER_DEPS := 
C_DEPS := 
CCM_UPPER_DEPS := 
SRC_DEPS := 
CC_DEPS := 
PP_DEPS := 
SX_DEPS := 
C++_DEPS := 
OBJS := 
ASM_DEPS := 
MAP := 
S_UPPER_DEPS := 
C++M_DEPS := 
CPP_DEPS := 

# Every subdirectory with source files must be described here
SUBDIRS := \
ra/arm/CMSIS_6 \
ra/fsp/src/bsp/cmsis/Device/RENESAS/Source \
ra/fsp/src/bsp/mcu/all \
ra/fsp/src/bsp/mcu/ra6m5 \
ra/fsp/src/r_iic_master \
ra/fsp/src/r_ioport \
ra/fsp/src/r_sci_uart \
ra/fsp/src/r_spi \
ra_gen \
src \
src/edge-impulse-sdk/CMSIS/DSP/Source/BasicMathFunctions \
src/edge-impulse-sdk/CMSIS/DSP/Source/BayesFunctions \
src/edge-impulse-sdk/CMSIS/DSP/Source/CommonTables \
src/edge-impulse-sdk/CMSIS/DSP/Source/ComplexMathFunctions \
src/edge-impulse-sdk/CMSIS/DSP/Source/ControllerFunctions \
src/edge-impulse-sdk/CMSIS/DSP/Source/DistanceFunctions \
src/edge-impulse-sdk/CMSIS/DSP/Source/FastMathFunctions \
src/edge-impulse-sdk/CMSIS/DSP/Source/FilteringFunctions \
src/edge-impulse-sdk/CMSIS/DSP/Source/InterpolationFunctions \
src/edge-impulse-sdk/CMSIS/DSP/Source/MatrixFunctions \
src/edge-impulse-sdk/CMSIS/DSP/Source/QuaternionMathFunctions \
src/edge-impulse-sdk/CMSIS/DSP/Source/SVMFunctions \
src/edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions \
src/edge-impulse-sdk/CMSIS/DSP/Source/SupportFunctions \
src/edge-impulse-sdk/CMSIS/DSP/Source/TransformFunctions \
src/edge-impulse-sdk/CMSIS/NN/Source/ActivationFunctions \
src/edge-impulse-sdk/CMSIS/NN/Source/BasicMathFunctions \
src/edge-impulse-sdk/CMSIS/NN/Source/ConcatenationFunctions \
src/edge-impulse-sdk/CMSIS/NN/Source/ConvolutionFunctions \
src/edge-impulse-sdk/CMSIS/NN/Source/FullyConnectedFunctions \
src/edge-impulse-sdk/CMSIS/NN/Source/NNSupportFunctions \
src/edge-impulse-sdk/CMSIS/NN/Source/PoolingFunctions \
src/edge-impulse-sdk/CMSIS/NN/Source/ReshapeFunctions \
src/edge-impulse-sdk/CMSIS/NN/Source/SVDFunctions \
src/edge-impulse-sdk/CMSIS/NN/Source/SoftmaxFunctions \
src/edge-impulse-sdk \
src/edge-impulse-sdk/classifier \
src/edge-impulse-sdk/dsp/dct \
src/edge-impulse-sdk/dsp/image \
src/edge-impulse-sdk/dsp/kissfft \
src/edge-impulse-sdk/dsp \
src/edge-impulse-sdk/porting/ambiq \
src/edge-impulse-sdk/porting/android \
src/edge-impulse-sdk/porting/arduino \
src/edge-impulse-sdk/porting/brickml \
src/edge-impulse-sdk/porting/ceva-npn \
src/edge-impulse-sdk/porting/clib \
src/edge-impulse-sdk/porting/espressif/ESP-NN \
src/edge-impulse-sdk/porting/espressif/ESP-NN/src/activation_functions \
src/edge-impulse-sdk/porting/espressif/ESP-NN/src/basic_math \
src/edge-impulse-sdk/porting/espressif/ESP-NN/src/common \
src/edge-impulse-sdk/porting/espressif/ESP-NN/src/convolution \
src/edge-impulse-sdk/porting/espressif/ESP-NN/src/fully_connected \
src/edge-impulse-sdk/porting/espressif/ESP-NN/src/pooling \
src/edge-impulse-sdk/porting/espressif/ESP-NN/src/softmax \
src/edge-impulse-sdk/porting/espressif \
src/edge-impulse-sdk/porting/espressif/esp-dsp \
src/edge-impulse-sdk/porting/espressif/esp-dsp/modules/common/misc \
src/edge-impulse-sdk/porting/espressif/esp-dsp/modules/fft/fixed \
src/edge-impulse-sdk/porting/espressif/esp-dsp/modules/fft/float \
src/edge-impulse-sdk/porting/ethos-core-driver/src \
src/edge-impulse-sdk/porting/himax \
src/edge-impulse-sdk/porting/himax-we2 \
src/edge-impulse-sdk/porting/iar \
src/edge-impulse-sdk/porting/infineon-psoc62 \
src/edge-impulse-sdk/porting/mbed \
src/edge-impulse-sdk/porting/mingw32 \
src/edge-impulse-sdk/porting/particle \
src/edge-impulse-sdk/porting/posix \
src/edge-impulse-sdk/porting/raspberry \
src/edge-impulse-sdk/porting/renesas-ra \
src/edge-impulse-sdk/porting/seeed-vision-ai \
src/edge-impulse-sdk/porting/silabs \
src/edge-impulse-sdk/porting/sony \
src/edge-impulse-sdk/porting/stm32-cubeai \
src/edge-impulse-sdk/porting/synaptics \
src/edge-impulse-sdk/porting/ti \
src/edge-impulse-sdk/porting/zephyr \
src/edge-impulse-sdk/tensorflow \
src/edge-impulse-sdk/tensorflow/lite/c \
src/edge-impulse-sdk/tensorflow/lite/core/api \
src/edge-impulse-sdk/tensorflow/lite/kernels/custom \
src/edge-impulse-sdk/tensorflow/lite/kernels/internal \
src/edge-impulse-sdk/tensorflow/lite/kernels \
src/edge-impulse-sdk/tensorflow/lite/micro \
src/edge-impulse-sdk/tensorflow/lite/micro/kernels \
src/edge-impulse-sdk/tensorflow/lite/micro/memory_planner \
src/edge-impulse-sdk/third_party/arc_mli_package \
src/edge-impulse-sdk/third_party/gemmlowp \
src/tflite-model \

